PROBLEM_IDENTIFIED = "PROBLEM_IDENTIFIED"
ADD_LOGS = "ADD_LOGS"
THINKING_LOGS = [
    "Pythagora is crunching the numbers...",
    "Pythagora is deep in thought...",
    "Pythagora is analyzing your request...",
    "Pythagora is brewing up a solution...",
    "Pythagora is putting the pieces together...",
    "Pythagora is working its magic...",
    "Pythagora is crafting the perfect response...",
    "Pythagora is decoding your query...",
    "Pythagora is on the case...",
    "Pythagora is computing an answer...",
    "Pythagora is sorting through the data...",
    "Pythagora is gathering insights...",
    "Pythagora is making connections...",
    "Pythagora is tuning the algorithms...",
    "Pythagora is piecing together the puzzle...",
    "Pythagora is scanning the possibilities...",
    "Pythagora is engineering a response...",
    "Pythagora is building the answer...",
    "Pythagora is mapping out a solution...",
    "Pythagora is figuring this out for you...",
    "Pythagora is thinking hard right now...",
    "Pythagora is working for you, so relax!",
    "Pythagora might take some time to figure this out...",
]
