packages:
  - .
  - ui
  - packages/*
  - extensions/*

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - "acpx"
  - "openclaw"
  - "@buape/carbon"
  - "vite"
  - "@cloudflare/workers-types"
  - "@mariozechner/*"
  - "@typescript/native-preview*"
  - "@oxlint/*"
  - "@oxfmt/*"
  - "sqlite-vec"
  - "sqlite-vec-*"

onlyBuiltDependencies:
  - "@discordjs/opus"
  - "@lydell/node-pty"
  - "@matrix-org/matrix-sdk-crypto-nodejs"
  - "@napi-rs/canvas"
  - "@tloncorp/api"
  - "@whiskeysockets/baileys"
  - authenticate-pam
  - esbuild
  - node-llama-cpp
  - protobufjs
  - sharp

ignoredBuiltDependencies:
  - koffi
