[project]
name = "pythagora-core"
version = "1.2.5"
description = "Build complete apps using AI agents"
authors = [{ name = "Leon Ostrez", email = "leon@pythagora.ai" }]
requires-python = "~=3.9"
readme = "README.md"
license = { text = "FSL-1.1-MIT" }
keywords = [
    "ai",
    "llm",
]
dependencies = [
    "pydantic>=2.8.2,<3",
    "openai>=1.40.6,<2",
    "anthropic>=0.39.0,<0.40",
    "groq>=0.6.0,<0.7",
    "jinja2>=3.1.4,<4",
    "tiktoken>=0.8.0,<0.9",
    "sqlalchemy[asyncio]>=2.0.32,<3",
    "aiosqlite>=0.20.0,<0.21",
    "psutil>=5.9.8,<6",
    "httpx>=0.27.0,<0.28",
    "alembic>=1.13.2,<2",
    "python-dotenv>=1.0.1,<2",
    "prompt-toolkit>=3.0.48,<4",
    "jsonref>=1.1.0,<2",
    "tenacity==9.0.0",
]

[project.urls]
Homepage = "https://pythagora.ai"
Repository = "https://github.com/Pythagora-io/pythagora-core"

[dependency-groups]
dev = [
    "pytest>=8.1.1,<9",
    "ruff>=0.3.5,<0.4",
    "pytest-cov>=5.0.0,<6",
    "pytest-asyncio>=0.23.6,<0.24",
    "pytest-timeout>=2.3.1,<3",
    "pre-commit>=3.7.0,<4",
]

[[tool.uv.index]]
name = "PyPI"
url = "https://pypi.org/simple/"
default = true

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/legacy/"
explicit = true

[tool.hatch.build.targets.sdist]
include = ["./core"]

[tool.hatch.build.targets.wheel]
include = ["./core"]

[tool.hatch.build.targets.wheel.sources]
"./core" = "core"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
addopts = "-ra -q --cov=core --no-cov-on-fail --timeout 10"
pythonpath = ["."]

[tool.coverage.report]
exclude_lines = ["if TYPE_CHECKING:", "raise NotImplementedError()"]
omit = ["core/db/migrations/*", "core/templates/tpl/*"]

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py39"
lint.extend-select = ["I"]
