"""add state action info

Revision ID: 06e603d6e19a
Revises: dbc3fd7ef89b
Create Date: 2024-05-25 10:33:34.535522

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06e603d6e19a"
down_revision: Union[str, None] = "dbc3fd7ef89b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_states", schema=None) as batch_op:
        batch_op.add_column(sa.Column("action", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_states", schema=None) as batch_op:
        batch_op.drop_column("action")

    # ### end Alembic commands ###
