"""added complexity to specification

Revision ID: 4f79e6952354
Revises: 5b04ea6afce5
Create Date: 2024-05-16 18:01:49.024811

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f79e6952354"
down_revision: Union[str, None] = "5b04ea6afce5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("specifications", schema=None) as batch_op:
        batch_op.add_column(sa.Column("complexity", sa.String(), server_default="hard", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("specifications", schema=None) as batch_op:
        batch_op.drop_column("complexity")

    # ### end Alembic commands ###
