"""add agent info to llm request log

Revision ID: 5b04ea6afce5
Revises: fd206d3095d0
Create Date: 2024-05-12 11:07:40.271217

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b04ea6afce5"
down_revision: Union[str, None] = "fd206d3095d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("agent", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_requests", schema=None) as batch_op:
        batch_op.drop_column("agent")

    # ### end Alembic commands ###
