"""record prompt data

Revision ID: dbc3fd7ef89b
Revises: 4f79e6952354
Create Date: 2024-05-23 17:02:15.386028

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbc3fd7ef89b"
down_revision: Union[str, None] = "4f79e6952354"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("prompts", sa.JSON(), server_default="[]", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_requests", schema=None) as batch_op:
        batch_op.drop_column("prompts")

    # ### end Alembic commands ###
