from .base import BaseProjectTemplate, NoOptions


class ViteReactProjectTemplate(BaseProjectTemplate):
    stack = "backend"
    name = "vite_react"
    path = "vite_react"
    description = "Vite + React + Tailwind CSS + TypeScript + Shadcn"
    file_descriptions = {
        "components.json": "Configuration file for UI component library, defining schema, styling options, and resource paths.",
        "eslint.config.js": "ESLint configuration file for TypeScript and React, including plugins and custom rules.",
        "index.html": "Main HTML entry point with root div for React mounting and main.tsx script.",
        "package.json": "Project configuration with dependencies, scripts, and metadata.",
        "postcss.config.js": "PostCSS configuration with tailwindcss and autoprefixer plugins.",
        "src/App.css": "Main application styles including root layout and animations.",
        "src/App.tsx": "Main React component with layout structure and welcome message.",
        "src/components/Footer.tsx": "Footer component with privacy and terms links.",
        "src/components/Header.tsx": "Header component with navigation menu.",
        "src/components/ui/accordion.tsx": "Shadcn Accordion component. Exports Accordion, AccordionItem, AccordionButton, and AccordionPanel.",
        "src/components/ui/alert-dialog.tsx": "Shadcn Alert Dialog component. Exports   AlertDialog, AlertDialogPortal, AlertDialogOverlay, AlertDialogTrigger, AlertDialogContent, AlertDialogHeader, AlertDialogFooter, AlertDialogTitle, AlertDialogDescription, AlertDialogAction, AlertDialogCancel.",
        "src/components/ui/alert.tsx": "Shadcn Alert component. Exports Alert, AlertTitle, AlertDescription.",
        "src/components/ui/aspect-ratio.tsx": "Shadcn Aspect Ratio component. Exports AspectRatio.",
        "src/components/ui/avatar.tsx": "Shadcn Avatar component. Exports Avatar, AvatarImage, AvatarFallback.",
        "src/components/ui/badge.tsx": "Shadcn Badge component. Exports Badge, badgeVariants.",
        "src/components/ui/breadcrumb.tsx": "Shadcn Breadcrumb component. Exports Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator, BreadcrumbEllipsis.",
        "src/components/ui/button.tsx": "Shadcn Button component. Exports Button, buttonVariants.",
        "src/components/ui/calendar.tsx": "Shadcn Calendar component. Exports Calendar.",
        "src/components/ui/card.tsx": "Shadcn Card component. Exports Card, CardHeader, CardFooter, CardTitle, CardDescription, CardContent.",
        "src/components/ui/carousel.tsx": "Shadcn Carousel component. Exports type CarouselApi, Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext.",
        "src/components/ui/chart.tsx": "Shadcn Chart component. Exports ChartContainer, ChartTooltip, ChartTooltipContent, ChartLegend, ChartLegendContent, ChartStyle.",
        "src/components/ui/checkbox.tsx": "Shadcn Checkbox component. Exports Checkbox.",
        "src/components/ui/collapsible.tsx": "Shadcn Collapsible component. Exports Collapsible, CollapsibleTrigger, CollapsibleContent.",
        "src/components/ui/command.tsx": "Shadcn Command component. Exports Command, CommandDialog, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandItem, CommandShortcut, CommandSeparator.",
        "src/components/ui/context-menu.tsx": "Shadcn Context Menu component. Exports ContextMenu, ContextMenuTrigger, ContextMenuContent, ContextMenuItem, ContextMenuCheckboxItem, ContextMenuRadioItem, ContextMenuLabel, ContextMenuSeparator, ContextMenuShortcut, ContextMenuGroup, ContextMenuPortal, ContextMenuSub, ContextMenuSubContent, ContextMenuSubTrigger, ContextMenuRadioGroup.",
        "src/components/ui/dialog.tsx": "Shadcn Dialog component. Exports Dialog, DialogPortal, DialogOverlay, DialogClose, DialogTrigger, DialogContent, DialogHeader, DialogFooter, DialogTitle, DialogDescription.",
        "src/components/ui/drawer.tsx": "Shadcn Drawer component. Exports Drawer, DrawerPortal, DrawerOverlay, DrawerClose, DrawerTrigger, DrawerContent, DrawerHeader, DrawerFooter, DrawerTitle, DrawerDescription.",
        "src/components/ui/dropdown-menu.tsx": "Shadcn Dropdown Menu component. Exports DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuCheckboxItem, DropdownMenuRadioItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuGroup, DropdownMenuPortal, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuRadioGroup.",
        "src/components/ui/form.tsx": "Shadcn Form component. Exports useFormField, Form, FormField, FormLabel, FormItem, FormControl, FormDescription, FormMessage.",
        "src/components/ui/hover-card.tsx": "Shadcn Hover Card component. Exports HoverCard, HoverCardTrigger, HoverCardContent.",
        "src/components/ui/input-otp.tsx": "Shadcn Input OTP component. Exports InputOTP, InputOTPGroup, InputOTPSlot, InputOTPSeparator.",
        "src/components/ui/input.tsx": "Shadcn Input component. Exports Input.",
        "src/components/ui/label.tsx": "Shadcn Label component. Exports Label.",
        "src/components/ui/menubar.tsx": "Shadcn Menubar component. Exports Menubar, MenubarMenu, MenubarTrigger, MenubarContent, MenubarItem, MenubarSeparator, MenubarLabel, MenubarCheckboxItem, MenubarRadioGroup, MenubarRadioItem, MenubarPortal, MenubarSubContent, MenubarSubTrigger, MenubarGroup, MenubarSub, MenubarShortcut.",
        "src/components/ui/navigation-menu.tsx": "Shadcn Navigation Menu component. Exports navigationMenuTriggerStyle, NavigationMenu, NavigationMenuList, NavigationMenuItem, NavigationMenuContent, NavigationMenuTrigger, NavigationMenuLink, NavigationMenuIndicator, NavigationMenuViewport.",
        "src/components/ui/pagination.tsx": "Shadcn Pagination component. Exports Pagination, PaginationContent, PaginationEllipsis, PaginationItem, PaginationLink, PaginationNext, PaginationPrevious.",
        "src/components/ui/popover.tsx": "Shadcn Popover component. Exports Popover, PopoverTrigger, PopoverContent.",
        "src/components/ui/progress.tsx": "Shadcn Progress component. Exports Progress.",
        "src/components/ui/radio-group.tsx": "Shadcn Radio Group component. Exports RadioGroup, RadioGroupItem.",
        "src/components/ui/resizable.tsx": "Shadcn Resizable component. Exports ResizablePanelGroup, ResizablePanel, ResizableHandle.",
        "src/components/ui/scroll-area.tsx": "Shadcn Scroll Area component. Exports ScrollArea, ScrollBar.",
        "src/components/ui/select.tsx": "Shadcn Select component. Exports Select, SelectGroup, SelectValue, SelectTrigger, SelectContent, SelectLabel, SelectItem, SelectSeparator, SelectScrollUpButton, SelectScrollDownButton.",
        "src/components/ui/separator.tsx": "Shadcn Separator component. Exports Separator.",
        "src/components/ui/sheet.tsx": "Shadcn Sheet component. Exports Sheet, SheetPortal, SheetOverlay, SheetClose, SheetTrigger, SheetContent, SheetHeader, SheetFooter, SheetTitle, SheetDescription.",
        "src/components/ui/sidebar.tsx": "Shadcn Sidebar component. Exports Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupAction, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInput, SidebarInset, SidebarMenu, SidebarMenuAction, SidebarMenuBadge, SidebarMenuButton, SidebarMenuItem, SidebarMenuSkeleton, SidebarMenuSub, SidebarMenuSubButton, SidebarMenuSubItem, SidebarProvider, SidebarRail, SidebarSeparator, SidebarTrigger, useSidebar.",
        "src/components/ui/skeleton.tsx": "Shadcn Skeleton component. Exports Skeleton.",
        "src/components/ui/slider.tsx": "Shadcn Slider component. Exports Slider.",
        "src/components/ui/sonner.tsx": "Shadcn Sonner component. Exports Toaster.",
        "src/components/ui/switch.tsx": "Shadcn Switch component. Exports Switch.",
        "src/components/ui/table.tsx": "Shadcn Table component. Exports Table, TableBody, TableCell, TableFooter, TableHeader, TableHead, TableRow, TableCaption.",
        "src/components/ui/tabs.tsx": "Shadcn Tabs component. Exports Tabs, TabsList, TabsTrigger, TabsContent.",
        "src/components/ui/textarea.tsx": "Shadcn Textarea component. Exports Textarea.",
        "src/components/ui/toast.tsx": "Shadcn Toast component. Exports type ToastProps, type ToastActionElement, ToastProvider, ToastViewport, Toast, ToastTitle, ToastDescription, ToastClose, ToastAction.",
        "src/components/ui/toaster.tsx": "Shadcn Toaster component. Exports Toaster.",
        "src/components/ui/toggle-group.tsx": "Shadcn Toggle Group component. Exports ToggleGroup, ToggleGroupItem.",
        "src/components/ui/toggle.tsx": "Shadcn Toggle component. Exports Toggle, toggleVariants.",
        "src/components/ui/tooltip.tsx": "Shadcn Tooltip component. Exports Tooltip, TooltipTrigger, TooltipContent, TooltipProvider.",
        "src/hooks/use-mobile.tsx": "Custom hook for detecting mobile viewport.",
        "src/hooks/use-toast.ts": "Custom hook for managing toast notifications.",
        "src/index.css": "Global styles with Tailwind CSS configuration and theme variables.",
        "src/lib/utils.ts": "Utility functions for class name management.",
        "src/main.tsx": "Application entry point with React root rendering.",
        "src/vite-env.d.ts": "TypeScript declarations for Vite environment.",
        "tailwind.config.js": "Tailwind CSS configuration with theme customizations.",
        "tsconfig.app.json": "TypeScript configuration for application code.",
        "tsconfig.json": "Main TypeScript configuration with project references.",
        "tsconfig.node.json": "TypeScript configuration for Node.js environment.",
        "vite.config.ts": "Vite build tool configuration with React plugin and aliases.",
    }
    summary = "\n".join([])
    options_class = NoOptions
    options_description = ""
    relevant_files = [
        "components.json",
        "eslint.config.js",
        "index.html",
        "package.json",
        "postcss.config.js",
        "src/App.css",
        "src/App.tsx",
        "src/components/Footer.tsx",
        "src/components/Header.tsx",
        "src/hooks/use-mobile.tsx",
        "src/hooks/use-toast.ts",
        "src/index.css",
        "src/lib/utils.ts",
        "src/main.tsx",
        "src/vite-env.d.ts",
        "tailwind.config.js",
        "tsconfig.app.json",
        "tsconfig.json",
        "tsconfig.node.json",
        "vite.config.ts",
    ]

    async def install_hook(self):
        await self.process_manager.run_command("npm install")
